# Generated by Django 5.1.6 on 2025-03-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('message', 'Message'), ('announcement', 'Announcement'), ('notification', 'Notification')], max_length=50),
        ),
    ]
