# Generated by Django 5.1.6 on 2025-04-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='course',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='semester',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='year',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('COCIS', 'COCIS'), ('COBAMS', 'COBAMS'), ('CONAS', 'CONAS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='student', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='department',
            field=models.CharField(choices=[('COCIS', 'COCIS'), ('COBAMS', 'COBAMS'), ('CONAS', 'CONAS')], max_length=10),
        ),
    ]
