# Generated by Django 5.1.6 on 2025-04-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_alter_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Marks', 'Marks'), ('Attendance', 'Attendance'), ('Resources', 'Resources'), ('Environmental', 'Environmental'), ('Conduct', 'Conduct'), ('Schedules', 'Schedules'), ('Other', 'Other')], default='student', max_length=100),
        ),
    ]
