# Generated by Django 5.1.6 on 2025-04-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_alter_issue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(default='Low', max_length=10),
        ),
    ]
