# Generated by Django 5.1.6 on 2025-04-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0011_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='progress',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
