# Generated by Django 5.1.6 on 2025-04-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0012_issue_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_id_sender',
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='deadline',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
