# Generated by Django 5.1.6 on 2025-04-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0013_remove_notification_user_id_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
    ]
