# Generated by Django 5.1.6 on 2025-05-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0018_issue_attachment_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_verified',
        ),
    ]
