# Generated by Django 5.1.5 on 2025-04-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='attachmet',
            field=models.FileField(blank=True, null=True, upload_to='issue_attachments/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_images/'),
        ),
    ]
