# Generated by Django 5.1.6 on 2025-03-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_department_alter_issue_department_log_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='department',
            field=models.CharField(choices=[('cocis', 'CoCIS'), ('cobams', 'CoBAMS'), ('conas', 'CoNAS'), ('cedat', 'CEDAT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('cocis', 'CoCIS'), ('cobams', 'CoBAMS'), ('conas', 'CoNAS'), ('cedat', 'CEDAT')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
