# Generated by Django 5.2 on 2025-04-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_issue_attachmet_issue_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='attachmet',
            new_name='attachment',
        ),
    ]
