# Generated by Django 5.1.6 on 2025-03-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_alter_issue_department_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('marks', 'Missing Marks'), ('attendance', 'Attendance'), ('resources', 'Resources'), ('environment', 'Environmental'), ('conduct', 'Conduct'), ('schedules', 'Schedules')], default='student', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('registrar', 'Registrar'), ('admin', 'Admin')], max_length=100),
        ),
    ]
