# Generated by Django 5.1.6 on 2025-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_issue_category_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.CharField(choices=[('CC1000', 'Electrical'), ('CC1100', 'Civil'), ('CC1200', 'Mechanical'), ('CC1300', 'Chemical')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
