# Generated by Django 5.2 on 2025-04-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_rename_attachmet_issue_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recovery_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
