# Generated by Django 5.2 on 2025-05-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_customuser_recovery_email_customuser_recovery_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
