# Generated by Django 5.1.6 on 2025-03-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_customuser_course_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(default='Unseen', max_length=10),
        ),
    ]
