# Generated by Django 5.1.6 on 2025-04-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Marks', 'Marks'), ('Attendance', 'Attendance'), ('Resources', 'Resources'), ('Environmental', 'Environmental'), ('Conduct', 'Conduct'), ('Schedules', 'Schedules')], default='student', max_length=100),
        ),
    ]
