# Generated by Django 5.1.6 on 2025-04-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_issue'),
        ('logbook', '0007_alter_issue_category'),
    ]

    operations = [
    ]
