# Generated by Django 5.2 on 2025-05-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_alter_customuser_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
