# Generated by Django 5.1.6 on 2025-04-03 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_merge_0002_issue_0007_alter_issue_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assignee',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Marks', 'Marks'), ('Attendance', 'Attendance'), ('Resources', 'Resources'), ('Environmental', 'Environmental'), ('Conduct', 'Conduct'), ('Schedules', 'Schedules'), ('Other', 'Other')], default='student', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='course_unit',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='department',
            field=models.CharField(choices=[('COCIS', 'COCIS'), ('COBAMS', 'COBAMS'), ('CONAS', 'CONAS')], default='none', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='semester',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='year',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('COCIS', 'COCIS'), ('COBAMS', 'COBAMS'), ('CONAS', 'CONAS')], default='Null', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(default='Unseen', max_length=10),
        ),
    ]
