# Generated by Django 5.2 on 2025-05-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='theme',
        ),
    ]
