# Generated by Django 5.1.6 on 2025-04-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_issue_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='deadline',
            field=models.DateField(default=''),
        ),
    ]
