# Generated by Django 5.1.6 on 2025-04-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_rename_assignee_issue_created_by_issue_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('COCIS', 'COCIS'), ('COBAMS', 'COBAMS'), ('CONAS', 'CONAS')], max_length=10),
        ),
    ]
