# Generated by Django 5.1.6 on 2025-04-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0010_alter_issue_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('notification', 'Notification')], max_length=50),
        ),
    ]
