# Generated by Django 5.1.6 on 2025-05-02 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0016_alter_log_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_id_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
