# Generated by Django 5.1.6 on 2025-05-15 13:24

import logbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0017_alter_notification_user_id_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=logbook.models.upload_to),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('COCIS', 'COCIS'), ('COBAMS', 'COBAMS'), ('CONAS', 'CONAS'), ('CEDAT', 'CEDAT'), ('CAES', 'CAES'), ('CHUSS', 'CHUSS'), ('CHS', 'CHS'), ('LAW', 'LAW'), ('SCHOOL_OF_EDUCATION', 'School of Education'), ('SCHOOL_OF_BUSINESS', 'School of Business'), ('SCHOOL_OF_BUILT_ENVIRONMENT', 'School of Built Environment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='department',
            field=models.CharField(choices=[('COCIS', 'COCIS'), ('COBAMS', 'COBAMS'), ('CONAS', 'CONAS'), ('CEDAT', 'CEDAT'), ('CAES', 'CAES'), ('CHUSS', 'CHUSS'), ('CHS', 'CHS'), ('LAW', 'LAW'), ('SCHOOL_OF_EDUCATION', 'School of Education'), ('SCHOOL_OF_BUSINESS', 'School of Business'), ('SCHOOL_OF_BUILT_ENVIRONMENT', 'School of Built Environment')], max_length=100),
        ),
    ]
